
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpzgznlfjkzekbpdvmuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwemd6bmxmamt6ZWticGR2bXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTAzOTksImV4cCI6MjA2NTk4NjM5OX0.N2rCtOfij0YWuYqej7mWY6KxUhMUMhFvQVgsS4C0MjQ";

// Configure Supabase client with proper security settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'assetspek-web'
    }
  }
});
